apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: main-route
  namespace: kv
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  entryPoints:
    # - web        # Port 80
    - websecure  # Port 443 (recommended: have to enable TLS configured)
  routes:
    - match: Host(`a3store.mooo.com`) && PathPrefix(`/`)
    # - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: api-service
          port: 80
  tls:
    secretName: api-tls