[project]
name = "kv-node"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.123.5",
    "grpcio-tools>=1.76.0",
    "prometheus-client>=0.23.1",
    "requests>=2.32.5",
    "uvicorn>=0.38.0",
]
