apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kv-servicemonitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: kv-node
  namespaceSelector:
    matchNames:
      - kv
  endpoints:
  - port: gossip
    path: /metrics
    interval: 15s